flowchart LR

    OT1{{"<b>OT1</b><br/>MT1<br/>TT1"}}
    OT2{{"<b>OT2</b><br/>MT2<br/>TT2"}}
    OT3{{"<b>OT3</b><br/>MT3<br/>TT3"}}
    OT4{{"<b>OT4</b><br/>MT4<br/>TT3"}}
    OT5{{"<b>OT5</b><br/>MT4<br/>TT2"}}

    PT3 --> OT4
    PT3 --> OT5

    OT4 --> PT1
    OT5 --> PT1

    PT1 --> OT1
    PT1 --> OT3

    OT1 --> PT2
    OT3 --> PT4

    PT4 --> OT2

    OT2 --> PT2

    style OT1 fill:yellow,stroke:orange
    style OT2 fill:yellow,stroke:orange
    style OT3 fill:yellow,stroke:orange
    style OT4 fill:yellow,stroke:orange
    style OT5 fill:yellow,stroke:orange