classDiagram

    direction LR

    namespace SimulationModel {

        class SimStorage {
        }
        class SimJob {
            +order: Order
        }
        class SimRobot {
            +process() void
        }
        class SimMachine {
            +machine: Machine
            +process() void
        }
        class SimTool {
            +tool_type: ToolType
        }
        class SimCorridor {
            +corridor: Corridor
        }
        class SimLayout {
            +layout: Layout
        }

    }

    SimLayout o--> SimRobot: main

    SimCorridor o--> SimRobot: left/right

    SimStorage <.. SimRobot: pick/place
    
    SimRobot ..>"one" SimJob: carries

    SimStorage ..>"many" SimJob: stores
    SimStorage <--o SimMachine: in/out
    SimStorage <--o SimCorridor: left/right/main
    SimStorage "two"<--o SimLayout: front/back

    SimMachine ..>"one" SimJob: processes
    SimMachine o-->"many" SimTool: contains
    SimMachine ..>"one" SimTool: mounts

    style SimRobot fill:yellow,stroke:orange
    style SimJob fill:yellow,stroke:orange
    style SimMachine fill:yellow,stroke:orange
    style SimTool fill:yellow,stroke:orange
    style SimStorage fill:yellow,stroke:orange
    style SimCorridor fill:yellow,stroke:orange
    style SimLayout fill:yellow,stroke:orange